#!/bin/sh
if [ -d ~/atlassian-stash-1.3.0 ]
then
	echo 'Stash seems to be installed already. Skipping build.'
else
	echo 'Installing Stash...'
	curl -L http://www.atlassian.com/software/stash/downloads/binary/atlassian-stash-1.3.0.tar.gz | tar zx
	echo 'Installing my own files...'
	cp -a stash/. ~
	echo 'Done.'
fi
