#!/bin/sh
export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/
sed -i 's/#STASH_HOME=""/STASH_HOME="\/home\/dotcloud\/data"/' ~/atlassian-stash-1.3.0/bin/setenv.sh
sed -i 's/<Connector port="7990"/<Connector port="'$PORT_WWW'"/' ~/atlassian-stash-1.3.0/conf/server.xml
exec ~/atlassian-stash-1.3.0/bin/start-stash.sh -fg
